### ISSUE TITLE
baycomp_plotting-1.1.tar.gz on PyPI doesn't have LICENSE

### ISSUE THREAD

**Issue by yurivict** [mjuez/baycomp_plotting#1]
```
===>  Configuring for py37-baycomp-plotting-1.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 6, in <module>
    with open('LICENSE') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
*** Error code 1
```

**Comment by mjuez** [comment]
Hi @yurivict, thanks for sending your feedback.
I've just released a new version (1.1.1) which should fix the issue.
